name: Run tests

on:
  push:
    paths:
    - '**.jl'
    - '**.toml'
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '1']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          # https://discourse.julialang.org/t/running-ci-for-julia-1-6-on-github-macos-runners-seems-to-fail/116577/3
          # macOS-latest implies arm64, which isn't available for Julia 1.6, so skip that.
          - os: macOS-latest
            julia-version: 1.6

        include:
          # macOS-13 appears to be the last x64 macOS.
          - os: macOS-13
            julia-version: 1.6

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
